# Generated by Django 5.1.7 on 2025-03-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular User'), ('admin', 'Admin'), ('engineer', 'Engineer')], max_length=10),
        ),
    ]
